// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jarvismarket.proto

package jarvismarket

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AppType int32

const (
	AppType_APPTYPE_NORMAL  AppType = 0
	AppType_APPTYPE_SERVICE AppType = 1
)

var AppType_name = map[int32]string{
	0: "APPTYPE_NORMAL",
	1: "APPTYPE_SERVICE",
}
var AppType_value = map[string]int32{
	"APPTYPE_NORMAL":  0,
	"APPTYPE_SERVICE": 1,
}

func (x AppType) String() string {
	return proto.EnumName(AppType_name, int32(x))
}
func (AppType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_jarvismarket_170da2f6d3c96d96, []int{0}
}

type AppInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Author               string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	AuthorEmail          string   `protobuf:"bytes,3,opt,name=authorEmail,proto3" json:"authorEmail,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Keywords             []string `protobuf:"bytes,5,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Version              string   `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	InDocker             bool     `protobuf:"varint,7,opt,name=inDocker,proto3" json:"inDocker,omitempty"`
	Type                 AppType  `protobuf:"varint,8,opt,name=type,proto3,enum=jarvismarket.AppType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppInfo) Reset()         { *m = AppInfo{} }
func (m *AppInfo) String() string { return proto.CompactTextString(m) }
func (*AppInfo) ProtoMessage()    {}
func (*AppInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarvismarket_170da2f6d3c96d96, []int{0}
}
func (m *AppInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppInfo.Unmarshal(m, b)
}
func (m *AppInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppInfo.Marshal(b, m, deterministic)
}
func (dst *AppInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppInfo.Merge(dst, src)
}
func (m *AppInfo) XXX_Size() int {
	return xxx_messageInfo_AppInfo.Size(m)
}
func (m *AppInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AppInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AppInfo proto.InternalMessageInfo

func (m *AppInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppInfo) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *AppInfo) GetAuthorEmail() string {
	if m != nil {
		return m.AuthorEmail
	}
	return ""
}

func (m *AppInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AppInfo) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *AppInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *AppInfo) GetInDocker() bool {
	if m != nil {
		return m.InDocker
	}
	return false
}

func (m *AppInfo) GetType() AppType {
	if m != nil {
		return m.Type
	}
	return AppType_APPTYPE_NORMAL
}

func init() {
	proto.RegisterType((*AppInfo)(nil), "jarvismarket.AppInfo")
	proto.RegisterEnum("jarvismarket.AppType", AppType_name, AppType_value)
}

func init() { proto.RegisterFile("jarvismarket.proto", fileDescriptor_jarvismarket_170da2f6d3c96d96) }

var fileDescriptor_jarvismarket_170da2f6d3c96d96 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0x31, 0x0d, 0x49, 0x7a, 0x41, 0xa5, 0xba, 0x08, 0x64, 0x31, 0x59, 0x4c, 0x81, 0xa1,
	0x43, 0x79, 0x82, 0x08, 0x32, 0x54, 0xe2, 0x27, 0x32, 0x15, 0x12, 0x13, 0x32, 0xad, 0x11, 0x26,
	0x24, 0xb6, 0x1c, 0x53, 0x94, 0x17, 0x67, 0x46, 0x76, 0x69, 0x95, 0x6e, 0xf7, 0xfb, 0x7c, 0xce,
	0x70, 0x0c, 0xf8, 0x29, 0xec, 0x4a, 0xb5, 0xb5, 0xb0, 0x95, 0x74, 0x13, 0x63, 0xb5, 0xd3, 0x78,
	0xd4, 0x77, 0x17, 0xbf, 0x04, 0x92, 0xdc, 0x98, 0x59, 0xf3, 0xae, 0x11, 0x21, 0x6a, 0x44, 0x2d,
	0x29, 0x61, 0x24, 0x1b, 0xf2, 0x70, 0xe3, 0x19, 0xc4, 0xe2, 0xdb, 0x7d, 0x68, 0x4b, 0xf7, 0x83,
	0xfd, 0x27, 0x64, 0x70, 0xb8, 0xbe, 0x8a, 0x5a, 0xa8, 0x2f, 0x3a, 0x08, 0x8f, 0x7d, 0xe5, 0x13,
	0x4b, 0xd9, 0x2e, 0xac, 0x32, 0x4e, 0xe9, 0x86, 0x46, 0xeb, 0x44, 0x4f, 0xe1, 0x39, 0xa4, 0x95,
	0xec, 0x7e, 0xb4, 0x5d, 0xb6, 0xf4, 0x80, 0x0d, 0xb2, 0x21, 0xdf, 0x32, 0x52, 0x48, 0x56, 0xd2,
	0xb6, 0xbe, 0x19, 0x87, 0xe6, 0x06, 0x7d, 0x4b, 0x35, 0xb7, 0x7a, 0x51, 0x49, 0x4b, 0x13, 0x46,
	0xb2, 0x94, 0x6f, 0x19, 0x2f, 0x21, 0x72, 0x9d, 0x91, 0x34, 0x65, 0x24, 0x1b, 0x4d, 0x4f, 0x27,
	0x3b, 0xf3, 0x73, 0x63, 0xe6, 0x9d, 0x91, 0x3c, 0x44, 0xae, 0xa6, 0x61, 0xb7, 0x17, 0x88, 0x30,
	0xca, 0xcb, 0x72, 0xfe, 0x52, 0x16, 0xaf, 0x0f, 0x8f, 0xfc, 0x3e, 0xbf, 0x1b, 0xef, 0xe1, 0x09,
	0x1c, 0x6f, 0xdc, 0x53, 0xc1, 0x9f, 0x67, 0x37, 0xc5, 0x98, 0xbc, 0xc5, 0xe1, 0x07, 0xaf, 0xff,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x23, 0x21, 0x11, 0x57, 0x01, 0x00, 0x00,
}
