// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jarvismarket.proto

package jarvismarketpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AppType int32

const (
	AppType_APPTYPE_UNKNOW  AppType = 0
	AppType_APPTYPE_NORMAL  AppType = 1
	AppType_APPTYPE_SERVICE AppType = 2
)

var AppType_name = map[int32]string{
	0: "APPTYPE_UNKNOW",
	1: "APPTYPE_NORMAL",
	2: "APPTYPE_SERVICE",
}
var AppType_value = map[string]int32{
	"APPTYPE_UNKNOW":  0,
	"APPTYPE_NORMAL":  1,
	"APPTYPE_SERVICE": 2,
}

func (x AppType) String() string {
	return proto.EnumName(AppType_name, int32(x))
}
func (AppType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_jarvismarket_09d21f1df49f5da1, []int{0}
}

type AppInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Author               string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	AuthorEmail          string   `protobuf:"bytes,3,opt,name=authorEmail,proto3" json:"authorEmail,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Keywords             []string `protobuf:"bytes,5,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Version              string   `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	InDocker             bool     `protobuf:"varint,7,opt,name=inDocker,proto3" json:"inDocker,omitempty"`
	Type                 AppType  `protobuf:"varint,8,opt,name=type,proto3,enum=jarvismarketpb.AppType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppInfo) Reset()         { *m = AppInfo{} }
func (m *AppInfo) String() string { return proto.CompactTextString(m) }
func (*AppInfo) ProtoMessage()    {}
func (*AppInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarvismarket_09d21f1df49f5da1, []int{0}
}
func (m *AppInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppInfo.Unmarshal(m, b)
}
func (m *AppInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppInfo.Marshal(b, m, deterministic)
}
func (dst *AppInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppInfo.Merge(dst, src)
}
func (m *AppInfo) XXX_Size() int {
	return xxx_messageInfo_AppInfo.Size(m)
}
func (m *AppInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AppInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AppInfo proto.InternalMessageInfo

func (m *AppInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppInfo) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *AppInfo) GetAuthorEmail() string {
	if m != nil {
		return m.AuthorEmail
	}
	return ""
}

func (m *AppInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AppInfo) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *AppInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *AppInfo) GetInDocker() bool {
	if m != nil {
		return m.InDocker
	}
	return false
}

func (m *AppInfo) GetType() AppType {
	if m != nil {
		return m.Type
	}
	return AppType_APPTYPE_UNKNOW
}

type RepositoryInfo struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Apps                 []*AppInfo `protobuf:"bytes,100,rep,name=apps,proto3" json:"apps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RepositoryInfo) Reset()         { *m = RepositoryInfo{} }
func (m *RepositoryInfo) String() string { return proto.CompactTextString(m) }
func (*RepositoryInfo) ProtoMessage()    {}
func (*RepositoryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarvismarket_09d21f1df49f5da1, []int{1}
}
func (m *RepositoryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepositoryInfo.Unmarshal(m, b)
}
func (m *RepositoryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepositoryInfo.Marshal(b, m, deterministic)
}
func (dst *RepositoryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepositoryInfo.Merge(dst, src)
}
func (m *RepositoryInfo) XXX_Size() int {
	return xxx_messageInfo_RepositoryInfo.Size(m)
}
func (m *RepositoryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RepositoryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RepositoryInfo proto.InternalMessageInfo

func (m *RepositoryInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RepositoryInfo) GetApps() []*AppInfo {
	if m != nil {
		return m.Apps
	}
	return nil
}

func init() {
	proto.RegisterType((*AppInfo)(nil), "jarvismarketpb.AppInfo")
	proto.RegisterType((*RepositoryInfo)(nil), "jarvismarketpb.RepositoryInfo")
	proto.RegisterEnum("jarvismarketpb.AppType", AppType_name, AppType_value)
}

func init() { proto.RegisterFile("jarvismarket.proto", fileDescriptor_jarvismarket_09d21f1df49f5da1) }

var fileDescriptor_jarvismarket_09d21f1df49f5da1 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcf, 0x4a, 0x33, 0x31,
	0x14, 0xc5, 0xbf, 0x69, 0xe7, 0xeb, 0x9f, 0x5b, 0x18, 0xcb, 0x15, 0x34, 0xb8, 0x1a, 0xba, 0x1a,
	0x2c, 0x74, 0xa1, 0x4f, 0x30, 0xe8, 0x08, 0x45, 0x6d, 0x6b, 0xac, 0x8a, 0x2b, 0x49, 0xdb, 0x88,
	0xb1, 0x76, 0x72, 0x49, 0x62, 0x65, 0xde, 0xdc, 0xa5, 0x4c, 0x6a, 0xcb, 0x08, 0xba, 0xbb, 0xe7,
	0x97, 0x73, 0x12, 0x72, 0x2e, 0xe0, 0xab, 0x30, 0x6b, 0x65, 0x57, 0xc2, 0x2c, 0xa5, 0x1b, 0x90,
	0xd1, 0x4e, 0x63, 0x54, 0x65, 0x34, 0xeb, 0x7d, 0x06, 0xd0, 0x4c, 0x89, 0x86, 0xf9, 0xb3, 0x46,
	0x84, 0x30, 0x17, 0x2b, 0xc9, 0x82, 0x38, 0x48, 0xda, 0xdc, 0xcf, 0x78, 0x00, 0x0d, 0xf1, 0xee,
	0x5e, 0xb4, 0x61, 0x35, 0x4f, 0xbf, 0x15, 0xc6, 0xd0, 0xd9, 0x4c, 0xd9, 0x4a, 0xa8, 0x37, 0x56,
	0xf7, 0x87, 0x55, 0x54, 0x3a, 0x16, 0xd2, 0xce, 0x8d, 0x22, 0xa7, 0x74, 0xce, 0xc2, 0x8d, 0xa3,
	0x82, 0xf0, 0x08, 0x5a, 0x4b, 0x59, 0x7c, 0x68, 0xb3, 0xb0, 0xec, 0x7f, 0x5c, 0x4f, 0xda, 0x7c,
	0xa7, 0x91, 0x41, 0x73, 0x2d, 0x8d, 0x2d, 0x93, 0x0d, 0x9f, 0xdc, 0xca, 0x32, 0xa5, 0xf2, 0x73,
	0x3d, 0x5f, 0x4a, 0xc3, 0x9a, 0x71, 0x90, 0xb4, 0xf8, 0x4e, 0x63, 0x1f, 0x42, 0x57, 0x90, 0x64,
	0xad, 0x38, 0x48, 0xa2, 0x93, 0xc3, 0xc1, 0xcf, 0xcf, 0x0e, 0x52, 0xa2, 0x69, 0x41, 0x92, 0x7b,
	0x53, 0xef, 0x06, 0x22, 0x2e, 0x49, 0x5b, 0xe5, 0xb4, 0x29, 0xfe, 0x2c, 0xa0, 0x0f, 0xa1, 0x20,
	0xb2, 0x6c, 0x11, 0xd7, 0x93, 0xce, 0xaf, 0x57, 0x96, 0x51, 0xee, 0x4d, 0xc7, 0x17, 0xbe, 0xcc,
	0xf2, 0x0d, 0x44, 0x88, 0xd2, 0xc9, 0x64, 0xfa, 0x38, 0xc9, 0x9e, 0xee, 0x46, 0x97, 0xa3, 0xf1,
	0x43, 0xf7, 0x5f, 0x95, 0x8d, 0xc6, 0xfc, 0x3a, 0xbd, 0xea, 0x06, 0xb8, 0x0f, 0x7b, 0x5b, 0x76,
	0x9b, 0xf1, 0xfb, 0xe1, 0x59, 0xd6, 0xad, 0xcd, 0x1a, 0x7e, 0x59, 0xa7, 0x5f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x85, 0x2d, 0x39, 0x7b, 0xc2, 0x01, 0x00, 0x00,
}
